name: MorsMutualInsurance
main: de.herobrickhd.deathbuyback.DeathBuybackPlugin
version: 1.0.0
api-version: 1.21
author: HerobrickHD
description: Ein H채ndler-Plugin, das verlorene Inventare nach dem Tod r체ckkaufen l채sst.

commands:
  mmi:
    description: Adminbefehle f체r MMI
    usage: /mmi help
    permission: mmi.admin

permissions:
  mmi.admin:
    description: Erlaubt alle MMI-Befehle
    default: op
